### ISSUE TITLE
Bad String during Firebase steps

### ISSUE THREAD

**Issue by pgporada** [webhook/webhook-server-open#10]
Upon copy/pasting the code from https://github.com/webhook/webhook-server-open/blob/master/security.json into Firebase, I get a bad string error on line 67.

![screenshot from 2015-01-29 22 49 41](https://cloud.githubusercontent.com/assets/2382565/5970947/29454ec4-a809-11e4-9d13-217d136859f3.png)

**Comment by LtSquigs** [comment]
Yeah firebase's inline error checker freaks out because of how complicated our rules are, but its not really an error. If you hit save it should save and work fine.

**Comment by yeerkkiller1** [comment]
Firebase is actually complaining about the trailing commas in your objects.

For example, it would complain about `{".write": true,}`.

It still runs, but if you get a real error you might miss it because of the additional comma warning.

**Comment by pgporada** [comment]
Gotcha, thanks yeerkkiller1. It's been over a year since I last tried webhook. I've been meaning to give it another shot. Back then I didn't know about json linting either.
