### ISSUE TITLE
[self-host] Can't Delete Site

### ISSUE THREAD

**Issue by budparr** [webhook/webhook-server-open#11]
I'm getting the error:
```
========================================================
# The site themetest3,1sonnetmedia,1org/ is not owned by you
========================================================
# You must be an owner on a site to delete it.
```
I'm an owner in Firebase, so I'm guessing there's an issue with the rules.

**Comment by LtSquigs** [comment]
The delete command does not work on self hosted sites yet, working on porting those commands over soon, for now if you use self hosted stuff youll want to destroy them manually.

**Comment by budparr** [comment]
Good to know, and not a problem at all. So I can just delete the buckets on GCloud Storage and in my build folders then?

And, stupid question - the security rules in this folder are only for porting over to Firebase correct; they don't have any other role?

**Comment by LtSquigs** [comment]
Yep Yep

**Comment by budparr** [comment]
Cool, thanks
