### ISSUE TITLE
Possible to use Grunt Newer?

### ISSUE THREAD

**Issue by budparr** [webhook/webhook-server-open#12]
Hi guys - I wrote a [post](https://www.npmjs.com/package/grunt-newer) on the forums about build times for larger sites and that got me thinking about use-cases. I'd love to see some of the editorially driven sites I work on capable of using Webhook, but I think even a long-running blog would start to be a drag once it got to a few thousand pages.

I may be naïve, but it seems like [Grunt Newer](https://www.npmjs.com/package/grunt-newer), which says it runs "Grunt tasks with only those source files modified since the last successful run" would be a good solution.

Would love to hear what you think, particularly if this sort of thing isn't even a concern, or on the roadmap but in the far future.

**Comment by LtSquigs** [comment]
Grunt Newer wouldnt really work in this situation because of the way the generator and and such all work.

There are plans to optimize the build process in the future, unfortunately its going to require a lot of restructuring and a lot of time to get there.

**Comment by budparr** [comment]
Thanks
