### ISSUE TITLE
Question about security rules and Permission Denied with attempting to set owners.

### ISSUE THREAD

**Issue by budparr** [webhook/webhook-server-open#14]
So I'm getting errors when I try to change an user from any group to an owner.

```
[Warning] FIREBASE WARNING: set at /management/sites/www,example,1org/owners/budparr@sonnetmedia,1net failed: permission_denied  (vendor.min.js, line 21)
```
I'm not getting the error in my hosted sites, just self-hosted, yet I'd think that a) the source would be a) in the security rules, and b) the same as hosted. 

Any thoughts where I should be looking?

**Comment by LtSquigs** [comment]
Hey bud,

Thanks for finding this bug, there was an issue with the security rule around that field. When I adjusted the rules for a verificationless system (like self hosted sites) I forgot to remove a constraint that doesnt make sense in that case.

You can see the change here https://github.com/webhook/webhook-server-open/commit/20770d074585892cb6478c7232080bf8ff560e65

Sorry, and thanks for the feedback

**Comment by budparr** [comment]
Awesome thank you!
